-- Up Migration
-- Switch authentication from SMS OTP to admin-generated passwords.
--
-- Product decisions:
--   * Passwords are 8 alphanumeric characters, generated by the admin.
--   * Permanent (no auto-expiry) — admin regenerates on demand.
--   * Existing users get must_reset_password=true so they can never log in
--     until the admin generates an initial password for them.
--   * Self-registration is disabled: only admins create users.
--
-- The OTP infrastructure (otp_codes table, /auth/otp/* endpoints) is kept
-- in place but unused. We deprecate it instead of dropping it so we can
-- roll back quickly if anything goes wrong on prod.

-- 1. Password storage on users.
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS password_hash        text,
  ADD COLUMN IF NOT EXISTS password_updated_at  timestamptz,
  ADD COLUMN IF NOT EXISTS must_reset_password  boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS created_by_admin_id  uuid REFERENCES users(id) ON DELETE SET NULL;

-- All pre-existing accounts had no password — force regeneration before
-- they can ever log in again.
UPDATE users SET must_reset_password = true WHERE password_hash IS NULL;

-- 2. Login rate-limiting log. We count failed attempts per phone within
--    a 15-minute window. Cleaned up by a separate cron / on-write.
CREATE TABLE IF NOT EXISTS login_attempts (
  id           bigserial PRIMARY KEY,
  phone        citext NOT NULL,
  ip_address   text,
  user_agent   text,
  success      boolean NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS login_attempts_phone_time_idx
  ON login_attempts (phone, created_at DESC);

CREATE INDEX IF NOT EXISTS login_attempts_recent_idx
  ON login_attempts (created_at DESC);

-- 3. (Optional) Tag old otp_codes as deprecated for visibility. The
--    column is nullable so the migration is reversible without data loss.
ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS deprecated_at timestamptz;
UPDATE otp_codes SET deprecated_at = now() WHERE deprecated_at IS NULL;
