-- Restaurants directory shown in the rider mobile app and managed from the
-- admin back office. Bootstrapped from OpenStreetMap (via the existing POI
-- ingester) but enriched over time with editorial fields (photo, cuisine,
-- price level, description, ETA, rating, curated tags) that OSM doesn't
-- carry.
--
-- The shape intentionally overlaps with voiceloc_pois (lat/lng, name_default,
-- name_fr/ar/en, osm_value, popularity, raw_tags) so the same OSM JSON can
-- seed both. Restaurants stay in their own table though, because:
--   1. They have a *lot* more editorial metadata.
--   2. They're soft-deletable from the admin without affecting voice search.
--   3. The mobile app queries them with their own pagination / filters.
--
-- Primary key is a slug (TEXT) rather than UUID so deep links stay readable
-- ("/rider/restaurant/pizza-lina" vs an opaque UUID).

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS restaurants (
  -- Slug, e.g. 'pizza-lina'. Generated by the API when omitted on create.
  id              text PRIMARY KEY,

  -- Canonical display name.
  name            text NOT NULL,
  -- Localized variants — same conventions as voiceloc_pois.
  name_fr         text,
  name_ar         text,
  name_en         text,

  -- Editorial / display fields. All nullable so OSM seeds can land
  -- minimally and be enriched later from the admin UI.
  zone            text,                -- e.g. "Tevragh Zeina"
  cuisine         text,                -- 'mauritanien' | 'pizza' | 'burger' | …
  tags            text[] NOT NULL DEFAULT '{}',
  price_level     text,                -- '$' | '$$' | '$$$'
  rating          numeric(2,1),        -- 0.0 .. 5.0
  eta_min         integer,             -- delivery / pickup window, minutes
  eta_max         integer,
  description     text,
  photo           text,                -- URL (Unsplash, CDN, S3…)
  address         text,

  -- Geometry. PostGIS isn't installed in this DB; lat/lng + btree indexes
  -- are plenty for a city-scale dataset.
  lat             double precision NOT NULL,
  lng             double precision NOT NULL,

  -- Ranking hint. Higher = top of the list. Seeded from OSM popularity,
  -- nudged by the editorial team.
  popularity      integer NOT NULL DEFAULT 0,

  -- OSM provenance (when seeded from the POI ingester). 'restaurant' |
  -- 'cafe' | 'fast_food' | NULL when curated by hand.
  osm_value       text,
  raw_tags        jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- Soft delete + audit. Hidden from the mobile app when is_active=false,
  -- but kept around so admins can restore mistakes.
  is_active       boolean NOT NULL DEFAULT true,

  created_by      uuid REFERENCES users(id) ON DELETE SET NULL,
  updated_by      uuid REFERENCES users(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT restaurants_eta_order_chk
    CHECK (eta_min IS NULL OR eta_max IS NULL OR eta_min <= eta_max),
  CONSTRAINT restaurants_price_chk
    CHECK (price_level IS NULL OR price_level IN ('$','$$','$$$')),
  CONSTRAINT restaurants_rating_chk
    CHECK (rating IS NULL OR (rating >= 0 AND rating <= 5))
);

-- The list endpoint scans active rows ordered by popularity DESC, name ASC.
CREATE INDEX IF NOT EXISTS restaurants_active_popularity_idx
  ON restaurants (popularity DESC, name) WHERE is_active = true;

-- Category-filter shortcut.
CREATE INDEX IF NOT EXISTS restaurants_cuisine_idx
  ON restaurants (cuisine) WHERE is_active = true;

-- Fuzzy name search (the mobile screen has a search bar).
CREATE INDEX IF NOT EXISTS restaurants_name_trgm_idx
  ON restaurants USING gin (lower(name) gin_trgm_ops);
