/**
 * Admin login — phone + admin-generated password.
 *
 * Replaces the previous OTP-by-SMS flow. The admin's initial password is
 * either bootstrapped in the database (first admin) or generated by an
 * existing admin via /admin/users.
 */

'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { api } from '@/lib/api';
import { useAuth } from '@/lib/auth';

const DEVICE_ID_PREFIX = 'tewiz-admin-web-';

export default function LoginPage() {
  const router = useRouter();
  const setSession = useAuth((s) => s.setSession);
  const user = useAuth((s) => s.user);
  const hydrate = useAuth((s) => s.hydrate);
  const hydrated = useAuth((s) => s.hydrated);

  const [phone, setPhone] = useState('+222');
  const [password, setPassword] = useState('');
  const [showPwd, setShowPwd] = useState(false);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => { hydrate(); }, [hydrate]);
  useEffect(() => {
    if (hydrated && user?.role === 'admin') router.replace('/applications');
  }, [hydrated, user, router]);

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    setBusy(true);
    setErr(null);
    try {
      const deviceId =
        DEVICE_ID_PREFIX +
        (typeof window !== 'undefined' && window.crypto?.randomUUID
          ? window.crypto.randomUUID().slice(0, 12)
          : Math.random().toString(36).slice(2, 14));

      const r = await api.post('/auth/login', {
        phone,
        password,
        role: 'admin',
        deviceId,
      });

      await setSession({
        user: r.data.user,
        accessToken: r.data.tokens.accessToken,
        refreshToken: r.data.tokens.refreshToken,
      });
      router.replace('/applications');
    } catch (e: any) {
      const code = e.response?.data?.error?.code;
      const status = e.response?.status;
      if (status === 401 || code === 'invalid_credentials') {
        setErr('Numéro ou mot de passe incorrect.');
      } else if (status === 403 && code === 'no_password_set') {
        setErr('Aucun mot de passe défini sur ce compte. Contactez un admin existant pour qu\'il en génère un.');
      } else if (status === 403 && code === 'role_mismatch') {
        setErr('Ce compte n\'est pas administrateur.');
      } else if (status === 429) {
        setErr(e.response?.data?.error?.message ?? 'Trop d\'essais — réessayez dans quelques minutes.');
      } else if (!e.response) {
        setErr(`Impossible de joindre l'API. (${e.message ?? 'unknown'})`);
      } else {
        setErr(e.response?.data?.error?.message ?? 'Erreur de connexion.');
      }
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-slate-50 p-4">
      <div className="card w-full max-w-md p-8">
        <div className="mb-8 text-center">
          <h1 className="text-2xl font-semibold text-slate-900">Tewiz Admin</h1>
          <p className="text-sm text-slate-500 mt-1">
            Connexion par téléphone et mot de passe
          </p>
        </div>

        <form onSubmit={submit} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">
              Numéro de téléphone
            </label>
            <input
              type="tel" required value={phone}
              onChange={(e) => setPhone(e.target.value)}
              placeholder="+22245XXXXXXX"
              className="input"
              autoComplete="username"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">
              Mot de passe
            </label>
            <div className="relative">
              <input
                type={showPwd ? 'text' : 'password'}
                required value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="••••••••"
                className="input pr-16 font-mono"
                autoComplete="current-password"
                minLength={4}
                maxLength={32}
              />
              <button
                type="button"
                onClick={() => setShowPwd((v) => !v)}
                className="absolute right-2 top-1/2 -translate-y-1/2 text-xs text-emerald-700 hover:text-emerald-900 font-semibold px-2 py-1"
              >
                {showPwd ? 'Cacher' : 'Voir'}
              </button>
            </div>
          </div>

          {err && (
            <p className="text-sm text-red-600 bg-red-50 border border-red-200 rounded-lg p-2">
              {err}
            </p>
          )}

          <button
            type="submit" disabled={busy}
            className="btn-primary w-full"
          >
            {busy ? 'Connexion…' : 'Se connecter'}
          </button>
        </form>

        <p className="text-xs text-slate-500 text-center mt-6">
          Pas de SMS — votre mot de passe vous a été transmis par un administrateur.
        </p>
      </div>
    </div>
  );
}
