export const MAURITANIA_CITIES = [
  'Nouakchott',
  'Nouadhibou',
  'Atar',
  'Kiffa',
  'Kaedi',
  'Rosso',
  'Zouerate',
  'Nema',
  'Aleg',
  'Tidjikja',
  'Selibaby',
  'Aioun el Atrouss',
  'Akjoujt',
  'Boutilimit',
  'Bir Moghrein',
  'Timbedra',
  'Guerou',
  'Magta Lahjar',
] as const;
