/**
 * Admin-generated password authentication.
 *
 * Product rules:
 *   - Passwords are 8 characters, alphanumeric (A-Z, a-z, 0-9).
 *   - They are generated by an admin and shown ONCE on the admin web,
 *     then the admin sends them to the user via WhatsApp.
 *   - Permanent: no expiry. Admin can regenerate at any time.
 *   - Rate-limited: at most 5 failed login attempts per phone per 15 min.
 */

import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import { pool } from '../../db/pool.js';
import { HttpError } from '../../middleware/error.js';

const PASSWORD_LENGTH = 8;
// A-Z + a-z + 0-9 minus visually-ambiguous characters (0/O, 1/l/I).
// Keeps the generated password unambiguous when sent over WhatsApp.
const ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789';

const BCRYPT_COST = 10;
const MAX_FAILED_ATTEMPTS = 5;
const RATE_WINDOW_MINUTES = 15;

/**
 * Generate a random 8-char password using a cryptographically secure RNG.
 * Always returns 8 characters from the safe alphabet.
 */
export function generatePassword(): string {
  const bytes = crypto.randomBytes(PASSWORD_LENGTH * 2); // over-sample
  let out = '';
  for (let i = 0; i < bytes.length && out.length < PASSWORD_LENGTH; i++) {
    const idx = bytes[i]! % ALPHABET.length;
    out += ALPHABET[idx];
  }
  return out;
}

export async function hashPassword(plain: string): Promise<string> {
  return bcrypt.hash(plain, BCRYPT_COST);
}

export async function verifyPassword(plain: string, hash: string): Promise<boolean> {
  return bcrypt.compare(plain, hash);
}

/**
 * Record a login attempt and optionally throw if the phone is currently
 * rate-limited. We record before checking the password, but only block
 * BEFORE consuming the password if there are already too many failures.
 */
export async function assertNotRateLimited(phone: string): Promise<void> {
  const { rows } = await pool.query<{ count: string }>(
    `SELECT COUNT(*) AS count
       FROM login_attempts
      WHERE phone = $1
        AND success = false
        AND created_at > now() - ($2 || ' minutes')::interval`,
    [phone, RATE_WINDOW_MINUTES.toString()],
  );
  const failed = parseInt(rows[0]?.count ?? '0', 10);
  if (failed >= MAX_FAILED_ATTEMPTS) {
    throw new HttpError(
      429,
      'too_many_attempts',
      `Trop d'essais. Réessayez dans ${RATE_WINDOW_MINUTES} minutes.`,
    );
  }
}

export async function recordAttempt(
  phone: string,
  success: boolean,
  ipAddress: string | null,
  userAgent: string | null,
): Promise<void> {
  await pool.query(
    `INSERT INTO login_attempts (phone, success, ip_address, user_agent)
     VALUES ($1, $2, $3, $4)`,
    [phone, success, ipAddress, userAgent],
  );
}
